name: Test TeachersPetBot

on:
  push:
    branches:
      - main
      - pylint
      - !Create_Fix
  pull_request:
    branches:
      - main
      - pylint
      - !Create_Fix

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint src
    - name: Create env file
      run: |
        cat << EOF > .env
        DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
        TESTING_BOT_TOKEN=${{ secrets.TESTING_BOT_TOKEN }}
        TEST_GUILD_ID=${{ secrets.TEST_GUILD_ID }}
        DICORD_BOT_NAME=${{ secrets.DICORD_BOT_NAME }}
        TEST_BOT_APP_ID=${{ secrets.TEST_BOT_APP_ID }}
        TEST_BOT_NAME=${{ secrets.TEST_BOT_NAME }}
        USERNAME=${{ secrets.USERNAME }}
        TEST_RECIPIENT_EMAIL=${{ secrets.TEST_RECIPIENT_EMAIL }}
        PASSWORD=${{ secrets.PASSWORD }}
        VERSION=${{ secrets.VERSION }}
        EOF
#     - name: Test with pytest
#       run: |
#         pytest
    - name: Run tests and collect coverage
      run: |
        (sleep 2; python3 -m pytest test/tests.py) & (coverage run --source=./src -m pytest src/bot.py )
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
